import { AiTool, Tutorial } from './types';

export const AI_TOOLS: AiTool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    slug: 'chatgpt',
    tagline: 'The world\'s most popular AI chatbot by OpenAI',
    description: 'ChatGPT is a large language model developed by OpenAI that can understand and generate human-like text. It can help with writing, coding, analysis, answering questions, and much more. Available in free and Plus tiers.',
    category: 'chatbot',
    tags: ['chatbot', 'writing', 'coding', 'analysis', 'openai'],
    pricing: 'freemium',
    pricingDetail: 'Free tier available. ChatGPT Plus at $20/month.',
    website: 'https://chat.openai.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    rating: 4.8,
    reviewCount: 12400,
    featured: true,
    isNew: false,
    pros: [
      'Extremely versatile - handles almost any text task',
      'Continuously improving with new updates',
      'Large community with tons of tutorials',
      'Code interpreter for data analysis',
    ],
    cons: [
      'Knowledge cutoff date (not always current)',
      'Can occasionally produce inaccurate information',
      'Plus tier required for GPT-4 access',
    ],
    useCases: ['Content writing', 'Code debugging', 'Research assistance', 'Language learning'],
    tutorialCount: 24,
    updatedAt: '2025-04-01',
  },
  {
    id: '2',
    name: 'Claude',
    slug: 'claude',
    tagline: 'Anthropic\'s advanced AI assistant focused on safety',
    description: 'Claude is an AI assistant by Anthropic, designed to be helpful, harmless, and honest. Claude excels at nuanced writing, long-form analysis, and complex reasoning tasks. Known for its large context window.',
    category: 'chatbot',
    tags: ['chatbot', 'writing', 'analysis', 'anthropic', 'long-context'],
    pricing: 'freemium',
    pricingDetail: 'Free tier available. Claude Pro at $20/month.',
    website: 'https://claude.ai',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Anthropic.svg/320px-Anthropic.svg.png',
    rating: 4.7,
    reviewCount: 8200,
    featured: true,
    isNew: false,
    pros: [
      '200K token context window',
      'Excellent at following complex instructions',
      'Strong writing quality and style consistency',
      'Better at refusing harmful requests',
    ],
    cons: [
      'Image generation not built-in',
      'Fewer integrations than ChatGPT',
      'Rate limits on free tier',
    ],
    useCases: ['Long document analysis', 'Complex writing tasks', 'Code review', 'Research summaries'],
    tutorialCount: 18,
    updatedAt: '2025-04-05',
  },
  {
    id: '3',
    name: 'Midjourney',
    slug: 'midjourney',
    tagline: 'The leading AI image generator for stunning visuals',
    description: 'Midjourney is an AI image generation tool that creates stunning artwork and visuals from text descriptions. It operates through Discord and produces some of the highest quality AI-generated images available.',
    category: 'image',
    tags: ['image generation', 'art', 'design', 'discord', 'creative'],
    pricing: 'paid',
    pricingDetail: 'Basic plan from $10/month. Standard at $30/month.',
    website: 'https://midjourney.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png',
    rating: 4.9,
    reviewCount: 15600,
    featured: true,
    isNew: false,
    pros: [
      'Highest quality AI image output',
      'Active community on Discord',
      'Wide variety of artistic styles',
      'Regular model updates (V6, V7)',
    ],
    cons: [
      'Requires Discord (no standalone app)',
      'No free tier',
      'Less control over precise details',
    ],
    useCases: ['Digital art creation', 'Marketing visuals', 'Concept art', 'Social media content'],
    tutorialCount: 31,
    updatedAt: '2025-03-20',
  },
  {
    id: '4',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    tagline: 'AI pair programmer that lives in your code editor',
    description: 'GitHub Copilot is an AI coding assistant that suggests code completions, writes functions from comments, and helps developers code faster. It integrates directly into VS Code, JetBrains, and other popular IDEs.',
    category: 'coding',
    tags: ['coding', 'programming', 'ide', 'github', 'autocomplete'],
    pricing: 'paid',
    pricingDetail: 'Individual at $10/month or $100/year. Free for students.',
    website: 'https://github.com/features/copilot',
    logo: 'https://github.gallerycdn.vsassets.io/extensions/github/copilot/1.196.0/1709753065714/Microsoft.VisualStudio.Services.Icons.Default',
    rating: 4.6,
    reviewCount: 9800,
    featured: true,
    isNew: false,
    pros: [
      'Seamless IDE integration',
      'Supports 40+ programming languages',
      'Context-aware suggestions',
      'Free for students and open source',
    ],
    cons: [
      'Suggestions can sometimes be inaccurate',
      'Requires internet connection',
      'Privacy concerns with proprietary code',
    ],
    useCases: ['Code autocomplete', 'Function generation', 'Test writing', 'Documentation'],
    tutorialCount: 15,
    updatedAt: '2025-03-28',
  },
  {
    id: '5',
    name: 'Cursor',
    slug: 'cursor',
    tagline: 'AI-first code editor built for pair programming with AI',
    description: 'Cursor is a code editor built from the ground up with AI integration. It can edit entire codebases, write code from natural language, and answer questions about your specific codebase in context.',
    category: 'coding',
    tags: ['coding', 'ide', 'editor', 'ai-native', 'pair programming'],
    pricing: 'freemium',
    pricingDetail: 'Free tier with 2000 completions/month. Pro at $20/month.',
    website: 'https://cursor.sh',
    logo: 'https://cursor.sh/favicon.ico',
    rating: 4.8,
    reviewCount: 6700,
    featured: true,
    isNew: false,
    pros: [
      'AI that understands your full codebase',
      'Natural language code editing',
      'Built on VS Code (familiar interface)',
      'Chat with your codebase feature',
    ],
    cons: [
      'Can be resource-intensive',
      'Paid tier needed for best models',
      'Occasional context window limitations',
    ],
    useCases: ['Full codebase refactoring', 'Bug fixing with context', 'New feature development', 'Code explanation'],
    tutorialCount: 12,
    updatedAt: '2025-04-10',
  },
  {
    id: '6',
    name: 'DALL-E 3',
    slug: 'dalle-3',
    tagline: 'OpenAI\'s powerful text-to-image AI model',
    description: 'DALL-E 3 is OpenAI\'s latest image generation model, integrated into ChatGPT Plus. It creates highly accurate images from detailed text prompts and is particularly good at following complex instructions.',
    category: 'image',
    tags: ['image generation', 'openai', 'text-to-image', 'creative'],
    pricing: 'freemium',
    pricingDetail: 'Included in ChatGPT Plus ($20/month). API usage per image.',
    website: 'https://openai.com/dall-e-3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    rating: 4.5,
    reviewCount: 5400,
    featured: false,
    isNew: false,
    pros: [
      'Excellent prompt adherence',
      'Integrated with ChatGPT',
      'Good at text within images',
      'Consistent quality',
    ],
    cons: [
      'Limited artistic styles vs Midjourney',
      'Strict content filters',
      'No standalone free access',
    ],
    useCases: ['Blog illustrations', 'Product mockups', 'Social media graphics', 'Presentation visuals'],
    tutorialCount: 9,
    updatedAt: '2025-02-15',
  },
  {
    id: '7',
    name: 'Jasper AI',
    slug: 'jasper-ai',
    tagline: 'AI writing platform built for marketing teams',
    description: 'Jasper is an enterprise AI writing assistant designed specifically for marketing content. It offers templates for ads, blog posts, emails, and social media content, with brand voice training capabilities.',
    category: 'writing',
    tags: ['writing', 'marketing', 'content', 'copywriting', 'enterprise'],
    pricing: 'paid',
    pricingDetail: 'Creator plan from $39/month. Teams from $99/month.',
    website: 'https://jasper.ai',
    logo: 'https://assets-global.website-files.com/60e5f2de011b86acebc30db7/66cf3d59af5b1fa8ed5bfb47_favicon.png',
    rating: 4.4,
    reviewCount: 7200,
    featured: false,
    isNew: false,
    pros: [
      '50+ content templates',
      'Brand voice training',
      'SEO integration with Surfer',
      'Team collaboration features',
    ],
    cons: [
      'More expensive than general AI tools',
      'Output quality depends on prompts',
      'Overkill for individual users',
    ],
    useCases: ['Marketing copy', 'Blog content at scale', 'Email campaigns', 'Ad variations'],
    tutorialCount: 8,
    updatedAt: '2025-01-30',
  },
  {
    id: '8',
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    tagline: 'AI-powered search engine with cited sources',
    description: 'Perplexity AI is an AI-powered search engine that provides direct answers with cited sources. Unlike traditional search, it understands natural language questions and synthesizes information from multiple sources.',
    category: 'research',
    tags: ['search', 'research', 'citations', 'real-time', 'information'],
    pricing: 'freemium',
    pricingDetail: 'Free tier available. Perplexity Pro at $20/month.',
    website: 'https://perplexity.ai',
    logo: 'https://www.perplexity.ai/favicon.svg',
    rating: 4.6,
    reviewCount: 4800,
    featured: false,
    isNew: false,
    pros: [
      'Real-time internet access',
      'Always provides source citations',
      'Great for factual research',
      'Follow-up questions support',
    ],
    cons: [
      'Less creative than other AI tools',
      'Pro required for advanced features',
      'Occasional source quality issues',
    ],
    useCases: ['Academic research', 'Fact checking', 'News summaries', 'Technical documentation lookup'],
    tutorialCount: 6,
    updatedAt: '2025-03-05',
  },
  {
    id: '9',
    name: 'Notion AI',
    slug: 'notion-ai',
    tagline: 'AI assistant built directly into your Notion workspace',
    description: 'Notion AI is an AI writing and productivity assistant integrated into the Notion workspace. It can summarize pages, generate content, translate text, and help you work more efficiently within your existing Notion setup.',
    category: 'productivity',
    tags: ['productivity', 'writing', 'notes', 'workspace', 'notion'],
    pricing: 'paid',
    pricingDetail: 'Notion AI add-on at $10/month per member.',
    website: 'https://notion.so/product/ai',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
    rating: 4.3,
    reviewCount: 3600,
    featured: false,
    isNew: false,
    pros: [
      'Seamlessly integrated with Notion',
      'Summarize and translate any page',
      'AI filling in databases',
      'No separate tool needed',
    ],
    cons: [
      'Only useful if you already use Notion',
      'Requires paid Notion + AI add-on',
      'Limited vs standalone AI tools',
    ],
    useCases: ['Meeting note summaries', 'Content drafting', 'Database automation', 'Document translation'],
    tutorialCount: 7,
    updatedAt: '2025-02-20',
  },
  {
    id: '10',
    name: 'Runway ML',
    slug: 'runway-ml',
    tagline: 'Professional AI video generation and editing platform',
    description: 'Runway ML is a creative AI platform focused on video generation, editing, and visual effects. It offers text-to-video, image-to-video, background removal, and over 30 AI-powered creative tools.',
    category: 'video',
    tags: ['video', 'generation', 'editing', 'creative', 'gen-2'],
    pricing: 'freemium',
    pricingDetail: 'Free 125 credits. Standard at $12/month. Unlimited at $76/month.',
    website: 'https://runwayml.com',
    logo: 'https://runwayml.com/favicon.ico',
    rating: 4.5,
    reviewCount: 5100,
    featured: false,
    isNew: false,
    pros: [
      'Text-to-video generation',
      'Professional video editing tools',
      '30+ AI magic tools',
      'High quality output',
    ],
    cons: [
      'Credits deplete quickly on free plan',
      'Video generation takes time',
      'Limited video length',
    ],
    useCases: ['Short video creation', 'Visual effects', 'Marketing videos', 'Creative projects'],
    tutorialCount: 10,
    updatedAt: '2025-03-15',
  },
  {
    id: '11',
    name: 'Surfer SEO',
    slug: 'surfer-seo',
    tagline: 'AI-powered SEO content optimization platform',
    description: 'Surfer SEO is an AI-powered platform that helps you create and optimize content for search engines. It analyzes top-ranking pages and provides real-time guidance to improve your content\'s SEO score.',
    category: 'seo',
    tags: ['seo', 'content optimization', 'marketing', 'keywords', 'rank'],
    pricing: 'paid',
    pricingDetail: 'Essential plan from $69/month. Scale at $149/month.',
    website: 'https://surferseo.com',
    logo: 'https://surferseo.com/favicon.ico',
    rating: 4.5,
    reviewCount: 4200,
    featured: false,
    isNew: false,
    pros: [
      'Real-time content score',
      'SERP analysis built-in',
      'Jasper AI integration',
      'Keyword research tools',
    ],
    cons: [
      'Expensive for small bloggers',
      'Learning curve for beginners',
      'Credits-based system for some features',
    ],
    useCases: ['Blog post optimization', 'Competitor analysis', 'Content briefs', 'Keyword planning'],
    tutorialCount: 8,
    updatedAt: '2025-01-25',
  },
  {
    id: '12',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    tagline: 'Hyper-realistic AI voice synthesis platform',
    description: 'ElevenLabs is an AI audio research company that creates the most realistic text-to-speech voices available. It offers voice cloning, multi-language support, and an API for building voice-enabled applications.',
    category: 'video',
    tags: ['text-to-speech', 'voice', 'audio', 'cloning', 'dubbing'],
    pricing: 'freemium',
    pricingDetail: 'Free 10,000 chars/month. Starter at $5/month.',
    website: 'https://elevenlabs.io',
    logo: 'https://elevenlabs.io/favicon.ico',
    rating: 4.7,
    reviewCount: 6300,
    featured: true,
    isNew: false,
    pros: [
      'Most realistic AI voices available',
      'Custom voice cloning',
      '29+ languages supported',
      'Extensive API access',
    ],
    cons: [
      'Voice cloning requires consent verification',
      'Monthly character limits',
      'Higher plans expensive for heavy users',
    ],
    useCases: ['Podcast creation', 'YouTube narration', 'App voice interfaces', 'Audiobook production'],
    tutorialCount: 9,
    updatedAt: '2025-04-01',
  },
];

export const TUTORIALS: Tutorial[] = [
  {
    id: '1',
    title: 'How to Use ChatGPT for Beginners: Complete 2025 Guide',
    slug: 'how-to-use-chatgpt-beginners-guide',
    toolName: 'ChatGPT',
    toolSlug: 'chatgpt',
    excerpt: 'Learn everything you need to know to get started with ChatGPT, from creating your account to writing effective prompts that get great results.',
    content: '',
    category: 'chatbot',
    difficulty: 'beginner',
    readTime: 8,
    publishedAt: '2025-03-01',
    updatedAt: '2025-04-01',
    featured: true,
  },
  {
    id: '2',
    title: 'ChatGPT Custom Instructions: The Ultimate Guide',
    slug: 'chatgpt-custom-instructions-guide',
    toolName: 'ChatGPT',
    toolSlug: 'chatgpt',
    excerpt: 'Discover how to set up ChatGPT custom instructions to make it remember your preferences and consistently deliver better, more personalized responses.',
    content: '',
    category: 'chatbot',
    difficulty: 'intermediate',
    readTime: 6,
    publishedAt: '2025-03-10',
    updatedAt: '2025-04-05',
    featured: false,
  },
  {
    id: '3',
    title: 'Midjourney V6 Tutorial: Master AI Art Generation',
    slug: 'midjourney-v6-tutorial-complete-guide',
    toolName: 'Midjourney',
    toolSlug: 'midjourney',
    excerpt: 'Step-by-step Midjourney V6 tutorial covering prompt writing, parameters, style references, and advanced techniques for creating stunning AI art.',
    content: '',
    category: 'image',
    difficulty: 'beginner',
    readTime: 12,
    publishedAt: '2025-02-15',
    updatedAt: '2025-03-20',
    featured: true,
  },
  {
    id: '4',
    title: 'GitHub Copilot vs Cursor: Which AI Coding Tool is Better?',
    slug: 'github-copilot-vs-cursor-comparison',
    toolName: 'GitHub Copilot',
    toolSlug: 'github-copilot',
    excerpt: 'Detailed comparison of GitHub Copilot and Cursor AI for developers. We test both tools across 10 real-world coding scenarios to find the winner.',
    content: '',
    category: 'coding',
    difficulty: 'intermediate',
    readTime: 10,
    publishedAt: '2025-03-25',
    updatedAt: '2025-04-10',
    featured: true,
  },
  {
    id: '5',
    title: 'How to Use Claude AI: Tips, Tricks & Best Prompts',
    slug: 'how-to-use-claude-ai-tips-tricks',
    toolName: 'Claude',
    toolSlug: 'claude',
    excerpt: 'Everything you need to know about using Claude AI effectively. Learn the best prompting strategies, use cases, and hidden features.',
    content: '',
    category: 'chatbot',
    difficulty: 'beginner',
    readTime: 7,
    publishedAt: '2025-03-15',
    updatedAt: '2025-04-05',
    featured: false,
  },
  {
    id: '6',
    title: 'How to Clone Your Voice with ElevenLabs (Step-by-Step)',
    slug: 'elevenlabs-voice-cloning-tutorial',
    toolName: 'ElevenLabs',
    toolSlug: 'elevenlabs',
    excerpt: 'Learn how to clone your voice using ElevenLabs AI in under 30 minutes. Covers sample recording, training, and using your cloned voice.',
    content: '',
    category: 'video',
    difficulty: 'beginner',
    readTime: 9,
    publishedAt: '2025-02-28',
    updatedAt: '2025-04-01',
    featured: false,
  },
  {
    id: '7',
    title: 'Cursor AI Tutorial: Build Apps 10x Faster with AI',
    slug: 'cursor-ai-tutorial-complete-guide',
    toolName: 'Cursor',
    toolSlug: 'cursor',
    excerpt: 'Master Cursor AI editor with this comprehensive tutorial. Learn codebase chat, AI code generation, and the features that make Cursor the best coding tool in 2025.',
    content: '',
    category: 'coding',
    difficulty: 'intermediate',
    readTime: 14,
    publishedAt: '2025-04-01',
    updatedAt: '2025-04-10',
    featured: true,
  },
  {
    id: '8',
    title: 'Perplexity AI vs ChatGPT: Which Is Better for Research?',
    slug: 'perplexity-ai-vs-chatgpt-research',
    toolName: 'Perplexity AI',
    toolSlug: 'perplexity-ai',
    excerpt: 'Comparing Perplexity AI and ChatGPT for research tasks. Which tool gives more accurate, up-to-date answers with reliable sources?',
    content: '',
    category: 'research',
    difficulty: 'beginner',
    readTime: 8,
    publishedAt: '2025-03-20',
    updatedAt: '2025-04-05',
    featured: false,
  },
];
